kind = "web"
previewPath = "/"
title = "BROKI INMOBILIARIA"
version = "1.0.0"
id = "artifacts/broki-inmobiliaria"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23033

[services.development]
run = "pnpm --filter @workspace/broki-inmobiliaria run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/broki-inmobiliaria", "run", "build" ]
publicDir = "artifacts/broki-inmobiliaria/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23033"
BASE_PATH = "/"
